import bmw3 from "../assets/bmw3.jpg";
import bmw4 from "../assets/bmw4.jpg";
import bmws from "../assets/bmws.jpg";
import volt from "../assets/volt.jpg";
import Callic from "../assets/Callic.jpg";
import toyo from "../assets/toyo.jpg";

export default [
  {
    id: 1,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "440",
    year: "2021",
  },

  {
    id: 2,
    car_name: "BMW 3 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW.",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "350",
    year: "2019",
  },

  {
    id: 3,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests.",
    quantity: "4",
    gas: "Gasoline",
    distance: "65.3km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "400",
    year: "2020",
  },
  {
    id: 4,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.7km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "620",
    year: "2020",
  },

  {
    id: 5,
    car_name: "BMW4 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.6km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "530",
    year: "2021",
  },

  {
    id: 6,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "490",
    year: "2019",
  },
  {
    id: 7,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: bmw3,
    price: "540",
    year: "2020",
  },

  {
    id: 8,
    car_name: "BMW3 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: volt,
    price: "340",
    year: "2021",
  },

  {
    id: 9,
    car_name: "RVolkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: Callic,
    price: "640",
    year: "2021",
  },
  {
    id: 10,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: toyo,
    price: "540",
    year: "2021",
  },

  {
    id: 11,
    car_name: "BMW3 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: bmw4,
    price: "340",
    year: "2021",
  },

  {
    id: 12,
    car_name: "RVolkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests.",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: bmws,
    price: "640",
    year: "2021",
  },
  {
    id: 13,
    car_name: "Toyota RAV3",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: bmw3,
    price: "540",
    year: "2020",
  },

  {
    id: 14,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: volt,
    price: "640",
    year: "2021",
  },

  {
    id: 15,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: toyo,
    price: "740",
    year: "2021",
  },
  {
    id: 16,
    car_name: "Toyota RAV5",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: Callic,
    price: "540",
    year: "2021",
  },

  {
    id: 17,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: bmws,
    price: "340",
    year: "2021",
  },

  {
    id: 18,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests.",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.1km/1-litre",
    mode: "autometic",
    imageUrl: bmw3,
    price: "400",
    year: "2021",
  },
  {
    id: 19,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future.",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.1km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "340",
    year: "2021",
  },

  {
    id: 20,
    car_name: "BMW 3 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW.",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "750",
    year: "2019",
  },

  {
    id: 21,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "65.3km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "500",
    year: "2020",
  },
  {
    id: 22,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.7km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "420",
    year: "2020",
  },

  {
    id: 23,
    car_name: "BMW4 GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.6km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "630",
    year: "2021",
  },

  {
    id: 24,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "590",
    year: "2019",
  },
  {
    id: 25,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "740",
    year: "2021",
  },

  {
    id: 26,
    car_name: "BMW 3 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "450",
    year: "2019",
  },

  {
    id: 27,
    car_name: "Volkswagen S-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "65.3km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "900",
    year: "2020",
  },
  {
    id: 28,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.7km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "820",
    year: "2020",
  },

  {
    id: 29,
    car_name: "BMW3 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.6km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "430",
    year: "2021",
  },

  {
    id: 30,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "690",
    year: "2019",
  },
  {
    id: 31,
    car_name: "Toyota RAV3",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "6.1km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "540",
    year: "2021",
  },

  {
    id: 32,
    car_name: "BMW 3 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "750",
    year: "2019",
  },

  {
    id: 33,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "65.3km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "800",
    year: "2020",
  },
  {
    id: 34,
    car_name: "Cadillac Escalade",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.7km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "520",
    year: "2020",
  },

  {
    id: 35,
    car_name: "BMW4 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Hybrid",
    distance: "9.6km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "730",
    year: "2021",
  },

  {
    id: 36,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "690",
    year: "2019",
  },
  {
    id: 37,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "7.1km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "540",
    year: "2021",
  },

  {
    id: 38,
    car_name: "BMW 3 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "9.2km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "450",
    year: "2019",
  },

  {
    id: 39,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.3km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "300",
    year: "2020",
  },
  {
    id: 40,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "9.7km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "720",
    year: "2020",
  },

  {
    id: 41,
    car_name: "BMW4 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.6km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "430",
    year: "2021",
  },

  {
    id: 42,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "590",
    year: "2019",
  },
  {
    id: 43,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "8.1km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "340",
    year: "2021",
  },

  {
    id: 44,
    car_name: "BMW 4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.2km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "550",
    year: "2019",
  },

  {
    id: 45,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.3km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "600",
    year: "2020",
  },
  {
    id: 46,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "9.7km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "520",
    year: "2020",
  },

  {
    id: 47,
    car_name: "BMW4 GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.6km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "430",
    year: "2021",
  },

  {
    id: 48,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "690",
    year: "2019",
  },
  {
    id: 49,
    car_name: "Toyota RAV4",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "9.1km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "340",
    year: "2021",
  },

  {
    id: 50,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.1km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "380",
    year: "2019",
  },

  {
    id: 51,
    car_name: "BMW 4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Hybrid",
    distance: "5.3km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "700",
    year: "2020",
  },
  {
    id: 52,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Gasoline",
    distance: "9.7km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "520",
    year: "2020",
  },

  {
    id: 53,
    car_name: "BMW4 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.6km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "630",
    year: "2021",
  },

  {
    id: 54,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "4.2km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "590",
    year: "2019",
  },
  {
    id: 55,
    car_name: "Toyota3 RAV",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Hybrid",
    distance: "9.7km/1-litre",
    mode: "Autometic",
    imageUrl: toyo,
    price: "640",
    year: "2021",
  },

  {
    id: 56,
    car_name: "BMW 4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.9km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "750",
    year: "2019",
  },

  {
    id: 57,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.3km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "600",
    year: "2020",
  },
  {
    id: 58,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.7km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "520",
    year: "2020",
  },

  {
    id: 59,
    car_name: "BMW3 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.6km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "430",
    year: "2021",
  },

  {
    id: 60,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "490",
    year: "2019",
  },
  {
    id: 56,
    car_name: "BMW 4 Series",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.9km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "750",
    year: "2019",
  },

  {
    id: 61,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.3km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "600",
    year: "2020",
  },
  {
    id: 62,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.7km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "520",
    year: "2020",
  },

  {
    id: 63,
    car_name: "BMW3 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.6km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "430",
    year: "2021",
  },

  {
    id: 64,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "490",
    year: "2019",
  },
  {
    id: 60,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "490",
    year: "2019",
  },
  {
    id: 56,
    car_name: "BMW 4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.9km/1-litre",
    mode: "Autometic",
    imageUrl: bmw4,
    price: "750",
    year: "2019",
  },

  {
    id: 61,
    car_name: "Volkswagen T-Cross",
    des: "The Volkswagen Taigun achieved 5 Stars in Global NCAP's updated crash tests",
    quantity: "4",
    gas: "Gasoline",
    distance: "6.3km/1-litre",
    mode: "Autometic",
    imageUrl: bmw3,
    price: "600",
    year: "2020",
  },
  {
    id: 62,
    car_name: "Cadillac Escalade",
    des: "Features that make a modern masterpiece ,experience the future in innovation.",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.7km/1-litre",
    mode: "Autometic",
    imageUrl: volt,
    price: "520",
    year: "2020",
  },

  {
    id: 63,
    car_name: "BMW3 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.6km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "430",
    year: "2021",
  },

  {
    id: 64,
    car_name: "BMW4 Series",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "8.2km/1-litre",
    mode: "Autometic",
    imageUrl: bmws,
    price: "490",
    year: "2019",
  },
  {
    id: 65,
    car_name: "BMW3 Series GTI",
    des: "Experience exceptional luxury and incredible innovations in the new BMW",
    quantity: "4",
    gas: "Gasoline",
    distance: "7.6km/1-litre",
    mode: "Autometic",
    imageUrl: Callic,
    price: "430",
    year: "2021",
  },
];
